### ISSUE TITLE
KNet shall introduce a PowerShell module

### ISSUE THREAD

**Issue by masesdevelopers** [masesgroup/KNet#100]
Is your feature request related to a problem? Please describe.
PowerShell is a great tool and an integration of it with Apache Kafka can be a plus.

Describe the solution you'd like
Create a module/snapin, based on KNet, to interact with Apache Kafka from PoweShell and publish it to [PowerShell Gallery](https://www.powershellgallery.com/). Maybe its name is **KNetPS**.

See https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/writing-portable-modules?view=powershell-7.2 for further information.

The list of CmdLet to be created are, at least, the command available in KNetCLI.

Describe alternatives you've considered
N/A

Additional context
See masesgroup/JNet#50

**Comment by masesdevelopers** [comment]
`JNetPSCore` package does no meet extensibility requirements. 
Seems tailored to the scope requested from `JNetPS`:
- `StartJNetPSCmdletCommandBase` is positional dependent.
- `JNetPSCore` is unuseful.
- Static method accessor shall be rewritten at all, there is no helper

**Comment by masesdevelopers** [comment]
A new version of JNet will be deployed soon which solves the issue.

**Comment by masesdevelopers** [comment]
Copy action within project shall be contextualized to avoid problems in inheritance of multiple *.targets file. Here the snippet which solves the problem:

```csproj
	<ItemGroup Condition="True">
		<jnetps_jars Include="$(ProjectDir)\..\..\..\jars\*.*" />
		<jnetps_config Include="$(ProjectDir)\..\..\config\*.*" />
		<jnetps_kraft Include="$(ProjectDir)\..\..\config\kraft\*.*" />
	</ItemGroup>

	<Target Name="CopyCustomContent" AfterTargets="AfterBuild">
		<Copy SourceFiles="@(jnetps_jars)" DestinationFolder="$(OutDir)\jars" />
		<Copy SourceFiles="@(jnetps_config)" DestinationFolder="$(OutDir)\config" />
		<Copy SourceFiles="@(jnetps_kraft)" DestinationFolder="$(OutDir)\config\kraft" />
	</Target>
	<Target Name="CopyCustomContentOnPublish" AfterTargets="Publish">
		<Copy SourceFiles="@(jnetps_jars)" DestinationFolder="$(OutDir)\jars" />
		<Copy SourceFiles="@(jnetps_config)" DestinationFolder="$(OutDir)\config" />
		<Copy SourceFiles="@(jnetps_kraft)" DestinationFolder="$(OutDir)\config\kraft" />
	</Target>
```

**Comment by masesdevelopers** [comment]
> Copy action within project shall be contextualized to avoid problems in inheritance of multiple *.targets file. Here the snippet which solves the problem:
> 
> ```
> 	<ItemGroup Condition="True">
> 		<jnetps_jars Include="$(ProjectDir)\..\..\..\jars\*.*" />
> 		<jnetps_config Include="$(ProjectDir)\..\..\config\*.*" />
> 		<jnetps_kraft Include="$(ProjectDir)\..\..\config\kraft\*.*" />
> 	</ItemGroup>
> 
> 	<Target Name="CopyCustomContent" AfterTargets="AfterBuild">
> 		<Copy SourceFiles="@(jnetps_jars)" DestinationFolder="$(OutDir)\jars" />
> 		<Copy SourceFiles="@(jnetps_config)" DestinationFolder="$(OutDir)\config" />
> 		<Copy SourceFiles="@(jnetps_kraft)" DestinationFolder="$(OutDir)\config\kraft" />
> 	</Target>
> 	<Target Name="CopyCustomContentOnPublish" AfterTargets="Publish">
> 		<Copy SourceFiles="@(jnetps_jars)" DestinationFolder="$(OutDir)\jars" />
> 		<Copy SourceFiles="@(jnetps_config)" DestinationFolder="$(OutDir)\config" />
> 		<Copy SourceFiles="@(jnetps_kraft)" DestinationFolder="$(OutDir)\config\kraft" />
> 	</Target>
> ```

The file mases.knet.targets shall be updated with the context

**Comment by masesdevelopers** [comment]
PowerShell process exit after execution of Java Main-Class.
During the test this particular behavior was highlighted: the Java Main-Class does not returns control to the cmdlet, but PowerShell process exit.

**Comment by mariomastrodicasa** [comment]
@masesdevelopers the file usagePS.md contains some typos and errors.
