### ISSUE TITLE
Update classes when JNet will evolve

### ISSUE THREAD

**Issue by masesdevelopers** [masesgroup/KNet#111]
**Is your feature request related to a problem? Please describe.**
Some classes miss implementation due to missing classes in JNet. 

**Describe the solution you'd like**
In issue masesgroup/JNet#75 new classes are requested, check it and update the referenced classes.

**Describe alternatives you've considered**
N/A

**Additional context**
See masesgroup/JNet#75

**Comment by mariomastrodicasa** [comment]
Classes listed in masesgroup/JNet/issues/75 refers to Apache Kafka Connect, but seems not used in KNet Connect SDK
