### ISSUE TITLE
It is useful to add some API to send back to Apache Kafka Connect logs from .NET side

### ISSUE THREAD

**Issue by masesdevelopers** [masesgroup/KNet#129]
It is useful to add some API to send back to Apache Kafka Connect logs from .NET side

_Originally posted by @masesdevelopers in https://github.com/masesgroup/KNet/issues/125#issuecomment-1322432333_

**Comment by mariomastrodicasa** [comment]
To produce a `SourceRecord` it is always mandatory to set the info shown below:
https://github.com/masesgroup/KNet/blob/c4f8919aac06f6bca0cc77f0e237830a9deca609/src/net/KNet/ClientSide/BridgedClasses/Connect/Source/SourceRecord.cs#L32

This issue asks to remove dependencies from types like `Map` which are Java types managed from JNet, what we can do on this?

**Comment by masesdevelopers** [comment]
> To produce a `SourceRecord` it is always mandatory to set the info shown below:
> 
> https://github.com/masesgroup/KNet/blob/c4f8919aac06f6bca0cc77f0e237830a9deca609/src/net/KNet/ClientSide/BridgedClasses/Connect/Source/SourceRecord.cs#L32

A pattern like this can solve:
```c#
new SourceRecord(OffsetForKey(KeyFieldName, keyToStore), OffsetAt(PositionFieldName, valueToStore), _DestinationTopic,...
```
