### ISSUE TITLE
Docker image for KNet Connect was not published

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KNet#143]
**Describe the bug**
Looking at the latest release [V1.4.7.0](https://github.com/masesgroup/KNet/releases/tag/V1.4.7.0): the package [mases.knetconnect](https://github.com/orgs/masesgroup/packages/container/package/mases.knetconnect) is listed, but inaccessible.

**To Reproduce**
1. Go to [mases.knetconnect](https://github.com/orgs/masesgroup/packages/container/package/mases.knetconnect)

**Expected behavior**
The Docker image for KNet Connect shall be available

**Screenshots**

**Desktop (please complete the following information):**
 - OS: None
 - Version 1.4.7

**Additional context**
N/A

**Comment by masesdevelopers** [comment]
Here the log on [workflow](https://github.com/masesgroup/KNet/actions/runs/3528666483/jobs/5919003660):

![image](https://user-images.githubusercontent.com/94312179/203608373-54899444-ae36-40ef-83b7-cf02c47d7843.png)

There is a 403 error from GitHub when the push was requested. We have to check if multiple images can be uploaded in the way the workflow was written or if there is a wrong configuration of the actions.

**Comment by masesdevelopers** [comment]
Seems that splitting the build Docker images action the issue is solved, tested in dedicated repo.

**Comment by masesdevelopers** [comment]
Last release have another issue. The README associated to KNetConnect on Nuget.org point out to CLI:
![image](https://user-images.githubusercontent.com/94312179/203672266-2dd2abb6-c0d1-453f-afbc-2f00c744fa76.png)
