### ISSUE TITLE
Update the method implementation to obtain a better performance

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KNet#148]
The following method:

https://github.com/masesgroup/KNet/blob/c4f8919aac06f6bca0cc77f0e237830a9deca609/src/net/KNet/ClientSide/BridgedClasses/Connect/KNetSourceTask.cs#L35

has two possible improvements:
- it is a chain of invocation which introduce too many avoidable calls between .NET and Java, moving it in Java it is possible to improve performance avoiding many JNI calls
- the return type can be `Map<string, V>` instead of `Map<string, object>`

**Comment by masesdevelopers** [comment]
The second point cannot be done due to this masesgroup/KNet#150
