### ISSUE TITLE
Change the type to Integer to admit null values

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KNet#149]
The following code does not accept `null` for partition:
https://github.com/masesgroup/KNet/blob/c4f8919aac06f6bca0cc77f0e237830a9deca609/src/net/KNet/ClientSide/BridgedClasses/Connect/Source/SourceRecord.cs#L52

The `null` is used to do not set partition and leave Apache Kafka free to choose it.

**Comment by masesdevelopers** [comment]
It can be changed in `int?` so we can avoid `Java.Lang.Integer` as requested from #129
