### ISSUE TITLE
Authenticode Signature Invalid

### ISSUE THREAD

**Issue by ShawnMSkyline** [masesgroup/KNet#170]
**Describe the bug**
When attempting to install the module in Powershell, I get the following error below.

**Command**
Install-Module -Name MASES.KNetPS

**Response**
"PackageManagement\Install-Package : The module 'MASES.KNetPS' cannot be installed or updated because the authenticode signature of the file 'MASES.KNetPS.cat' 
is not valid."

**To Reproduce**
1. Run Install-Module -Name MASES.KNetPS from powershell

**Expected behavior**
Installs the module like normal

**Screenshots**
PS C:\Windows\system32> Install-Module -Name MASES.KNetPS
PackageManagement\Install-Package : The module 'MASES.KNetPS' cannot be installed or updated because the authenticode signature of the file 'MASES.KNetPS.cat' 
is not valid.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 

PS C:\Windows\system32> Install-Module -Name MASES.KNetPS -RequiredVersion 1.4.4
PackageManagement\Install-Package : The module 'MASES.KNetPS' cannot be installed or updated because the authenticode signature of the file 'MASES.KNetPS.cat' 
is not valid.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 

**Desktop (please complete the following information):**
 - OS: Windows Server 2016 Standard
 - Version: 1607
 - PowerShell Version: 
PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                                                                                           
----                           -----                                                                                                                           
PSVersion                      5.1.14393.5582                                                                                                                  
PSEdition                      Desktop                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                         
BuildVersion                   10.0.14393.5582                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                 
WSManStackVersion              3.0                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                             
SerializationVersion           1.1.0.1  

**Additional context**

**Comment by masesdevelopers** [comment]
@ShawnMSkyline the [instructions page](https://github.com/masesgroup/KNet/blob/9bfd3493a25d7267cd778e26efe892748883e190/src/net/Documentation/articles/usagePS.md) shall be updated while the issue you reported is solved. The command to be issued in the PS shell is the following one and it works on both PowerShell Desktop and PowerShell Core:

```pwsh
Install-Module -Name MASES.KNetPS -SkipPublisherCheck
```
