### ISSUE TITLE
Using the artifact in PowerShell based on .NET Framework seems not possible to start and use the module

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KNet#185]
@masesdevelopers using the artifact in PowerShell based on .NET Framework seems not possible to start and use the module

_Originally posted by @mariomastrodicasa in https://github.com/masesgroup/KNet/issues/100#issuecomment-1604268830_

**Comment by masesdevelopers** [comment]
The problem is in the following row
https://github.com/masesgroup/KNet/blob/c4a6e648a9f113281fb7495c07349d8ea451f6fd/src/net/KNetPS/KNetPS.csproj#L4
While it produces a DLL for .NET 6, in .NET Framework it creates an executable.
