### ISSUE TITLE
Commands in PowerShell does not work

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KNet#187]
**Describe the bug**
Commands like `Start-ConsoleConsumer` does not work in latest PowerShell 7

**To Reproduce**
1. Open PowerShell Version 7
2. Execute `Import-Module MASES.KNetPS`
3. Execute `Start-ConsoleConsumer`
4. See error on PowerShell console reporting error related to redirection

**Expected behavior**
`Start-ConsoleConsumer` executes the corresponding command

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PowerShell 7.3.4

**Additional context**
In PowerShell 5 is not applicable due to #186

**Comment by masesdevelopers** [comment]
@mariomastrodicasa the issue is related to masesgroup/JNet#72: the capture of remote console starts before the process starts
