### ISSUE TITLE
Add Kafka Connect API

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KNet#19]
**Is your feature request related to a problem? Please describe.**
In #1 was missing the reference to other Kafka features like Connect. Add some of Kafka Connect classes

**Describe the solution you'd like**
Add classes which help to use Apache Kafka Connect.

**Describe alternatives you've considered**
N/A

**Additional context**
#1

**Comment by masesdevelopers** [comment]
Closed with #65
