### ISSUE TITLE
Add a benchmark to verify performance

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KNet#53]
**Is your feature request related to a problem? Please describe.**
The project needs a benchmark to verify its performance.

**Describe the solution you'd like**
Add some benchmark associated to the produce/consume API calls to verify performance and identify possible bottlenecks.

**Describe alternatives you've considered**
Introduce some counter or other mechanism to measure time like `Stopwatch`.

**Additional context**
N/A

**Comment by masesdevelopers** [comment]
The benchmark cannot be built with an absolute vision. What it can done is to have some function that executes in the same way, but use a different underlying mechanism: i.e. use KNet in some function and use e.g. Confluent.Kafka in other.
Pairing this two executions it is possible to compare both implementations.
Anyway it is mandatory to use configurations which, more or less, create similar environments: if the configuration is in one case, or in another, is optimized the comparison has no real meaning. The previous consideration comes from the number of possible options can be used when a consumer/producer is allocated, how the underlying mechanism manages message batching both in receive mode (consume) and send mode (produce).

**Comment by mariomastrodicasa** [comment]
@masesdevelopers: Add a new benchmark which measures the time elapsed from the moment where a record is sent from the producer to the reception of the same record from a consumer: it is like a roundtrip. I think this benchmark can measure both producer and consumer performance, maybe it is possible to use https://github.com/masesgroup/KNet/issues/53#issuecomment-1126036921

**Comment by masesdevelopers** [comment]
Since KNet supports `ByteBuffer` data transfer, integrates `ByteBuffer` on tests for KNet side to compare execution between the two transport plus `ByteBuffer` data transfer versus Confluent.Kafka
