### ISSUE TITLE
Byte Array raise a problem during consuming

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KNet#54]
**Describe the bug**
Using `byte[]` creates problem during data extraction.

**To Reproduce**
1. Use a consumer like `KafkaConsumer<int, byte[]>`
2. Try to consume using `Poll`
3. When data are received try to get the `Value` of the `ConsumerRecord<int, byte[]>`
4. An exception is raised

**Expected behavior**
The `byte[]` received shall be available to the API user.

**Desktop (please complete the following information):**
 - OS: All
 - Version: latest
 
**Additional context**
The exceptions seems be raised from JCOBridge: check if the call wasn't done in the correct way.

**Comment by masesdevelopers** [comment]
The issue comes from JCOBridge itself. When there are generic JVM reports the result as a `java.lang.Object`: this `java.lang.Object` must be analyzed to identify the real object and map it to the correct wrapper.
